// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using productionLine.Server.Model;

#nullable disable

namespace productionLine.Server.Migrations
{
    [DbContext(typeof(FormDbContext))]
    [Migration("20250407045808_approval")]
    partial class approval
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("productionLine.Server.Model.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FormLink")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FORMLINK")
                        .HasAnnotation("Relational:JsonPropertyName", "formLink");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NAME")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.ToTable("FF_FORM");
                });

            modelBuilder.Entity("productionLine.Server.Model.FormApprover", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdObjectId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("FormId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Level")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.ToTable("FormApprovers");
                });

            modelBuilder.Entity("productionLine.Server.Model.FormField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<bool?>("Decimal")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("DECIMAL");

                    b.Property<int>("FormId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FORMID");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("LABEL");

                    b.Property<double?>("Max")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("MAX");

                    b.Property<double?>("Min")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("MIN");

                    b.Property<string>("Options")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("OPTIONS");

                    b.Property<bool?>("RequireRemarksOutOfRange")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("REMARKS_OUT");

                    b.Property<bool>("Required")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("REQUIRED");

                    b.Property<string>("RequiresRemarks")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("REQUIRES_REMARKS");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TYPE");

                    b.Property<string>("Width")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("WIDTH");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.ToTable("FF_FORMFIELD");
                });

            modelBuilder.Entity("productionLine.Server.Model.FormSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FormId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FORMID");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("SUBMITTEDAT");

                    b.HasKey("Id");

                    b.ToTable("FF_FORMSUBMISSION");
                });

            modelBuilder.Entity("productionLine.Server.Model.FormSubmissionData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FieldLabel")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FIELDLABEL");

                    b.Property<string>("FieldValue")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FIELDVALUE");

                    b.Property<int>("FormSubmissionId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FORMSUBMISSIONID");

                    b.HasKey("Id");

                    b.HasIndex("FormSubmissionId");

                    b.ToTable("FF_FORMSUBMISSIONDATA");

                    b.HasAnnotation("Relational:JsonPropertyName", "submissionData");
                });

            modelBuilder.Entity("productionLine.Server.Model.RemarkTrigger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("FormFieldId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("FORMFIELDID");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("OPERATOR");

                    b.Property<double>("Value")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("VALUE");

                    b.HasKey("Id");

                    b.HasIndex("FormFieldId");

                    b.ToTable("FF_REMARK_TRIGGER");
                });

            modelBuilder.Entity("productionLine.Server.Model.FormApprover", b =>
                {
                    b.HasOne("productionLine.Server.Model.Form", "Form")
                        .WithMany("Approvers")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("productionLine.Server.Model.FormField", b =>
                {
                    b.HasOne("productionLine.Server.Model.Form", "Form")
                        .WithMany("Fields")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("productionLine.Server.Model.FormSubmissionData", b =>
                {
                    b.HasOne("productionLine.Server.Model.FormSubmission", "FormSubmission")
                        .WithMany("SubmissionData")
                        .HasForeignKey("FormSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormSubmission");
                });

            modelBuilder.Entity("productionLine.Server.Model.RemarkTrigger", b =>
                {
                    b.HasOne("productionLine.Server.Model.FormField", "FormField")
                        .WithMany("RemarkTriggers")
                        .HasForeignKey("FormFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormField");
                });

            modelBuilder.Entity("productionLine.Server.Model.Form", b =>
                {
                    b.Navigation("Approvers");

                    b.Navigation("Fields");
                });

            modelBuilder.Entity("productionLine.Server.Model.FormField", b =>
                {
                    b.Navigation("RemarkTriggers");
                });

            modelBuilder.Entity("productionLine.Server.Model.FormSubmission", b =>
                {
                    b.Navigation("SubmissionData");
                });
#pragma warning restore 612, 618
        }
    }
}
